from __future__ import annotations


DEFAULT_VU_LADDER: tuple[int, ...] = (10, 20, 40, 60)
DEFAULT_REPETITIONS = 3
DEFAULT_WARMUP_MINUTES = 10
DEFAULT_MEASURED_MINUTES = 20
DEFAULT_COOLDOWN_MINUTES = 5
DEFAULT_OUTPUT_ROOT = "outputs"
DEFAULT_WORKLOAD_TOOL = "hammerdb"

